### PR TITLE
Add support for Spark 2.4.0-hadoop2.7

### PR DESCRIPTION
**Pull request by shimamoto**
Spark 2.4.0 released!

Aside from this, I’m considering whether to add support for Spark 2.4.0 with Scala 2.12 or not. I would very much like to hear what you have to say.

### CODE REVIEW

**Comment by GezimSejdiu** [comment]
Hi @shimamoto ,

many thanks once more for your contribution by adding new Docker images for the latest Spark release. I also was considering doing that, adding Scala 2.12 since we may plan to use the same on [SANSA](https://github.com/SANSA-Stack) as well and would be great to experiment on it. Even, it is [marked as experimental on the Spark release notes](http://spark.apache.org/releases/spark-release-2-4-0.html), I guess it is okay to go with our hadoop 2.8 provided versions, since there is [no pre-build provided by Spark](http://spark.apache.org/downloads.html) 

Let me create a dedicated branch for your PR and then you change the target branch from `master` to `2.4.0-hadoop2.7`. I will create also dedicated branches for `2.4.0-hadoop2.8` and  `2.4.0-hadoop2.8-scala-2.12`, which mean we keep scala-2.12 version only for hadoop2.8 versions.

Best regards,

**Comment by shimamoto** [comment]
@GezimSejdiu thanks a lot! I have changed target branches.

> I will create also dedicated branches for 2.4.0-hadoop2.8 and 2.4.0-hadoop2.8-scala-2.12, which mean we keep scala-2.12 version only for hadoop2.8 versions.

I got it. I’ll give it a try.

**Comment by shimamoto** [comment]
What branch should I create the `2.4.0-hadoop2.8-scala-2.12` branch from?

**Comment by GezimSejdiu** [comment]
> What branch should I create the `2.4.0-hadoop2.8-scala-2.12` branch from?

After we merge a `2.4.0-hadoop2.8` branch (see : #48 ) than we can checkout that branch and create a scala2.12 version of it.

Best regards,

**Pull request merged**
