### PR TITLE
Update for Java 11 runtime

### PR DESCRIPTION
**Pull request by anatolyD**
Updated to use Java 11 on runtime

### CODE REVIEW

**Review by GezimSejdiu — COMMENTED** [review]
Hi @anatolyD , 

many thanks for your contributions to providing the docker version of Spark bundled with Java 11. That is great that Spark provides support for the OpenJDK 11 since [version 3.0.0](http://spark.apache.org/releases/spark-release-3-0-0.html) and it is a great contribution from your side to have it here as well. Thanks a lot for that. 

If we follow the master branch of Spark (default branch) it is still provided with [Java 8](https://github.com/apache/spark/blob/branch-3.0/pom.xml#L115) as a default Java and therefore we can also consider keeping Java 8 as master/latest branch in our case as well. So based on our naming conventions (at least how we did in the past) I can crate a branch (checked out from master)  i.e. `3.0.0-hadoop3.2-java11-scala2.12` and then you chose that branch as a target instead of pushing it to master? for sure, then you can also update the README on master branch to include that specific version of the docker version as you did it here. 

What do you think about this idea? Do you think (and maybe to others as well who are using the dockers) makes sense to move it to Java 11 as a master branch? For me, it shouldn't be an issue if we move to Java 11 but wanted to also take other opinions if any.

Best regards,

**Comment by anatolyD** [comment]
> I can crate a branch (checked out from master) i.e. `3.0.0-hadoop3.2-java11-scala2.12` and then you chose that branch as a target instead of pushing it to master?

Hi @GezimSejdiu ! I think this should work. I will appreciate if we can make it in. and prep docker containers out of it. Let me please know when can i redirect the branch. Thank you in advance!

**Comment by GezimSejdiu** [comment]
Hi @anatolyD , 

I just created the [3.0.0-hadoop3.2-java11](https://github.com/big-data-europe/docker-spark/tree/3.0.0-hadoop3.2-java11) branch. Could, you please redirect your PR against that branch? so we can move on with the merge. 

After that is done, you should also add one line of this support on the `master` branch (README file) which then let others know that they can also use java11 as a runtime and of course, you will be listed as a contributor to the project.

Once more, thanks a lot for your time and contribution.

Best regards, 
Gezim

**Comment by anatolyD** [comment]
i now think it is better to also upgrade to 3.0.1 as the main branch. will do later a bit

**Pull request merged**
