### PR TITLE
Update for Spark 3 and Hadoop 3.2

### PR DESCRIPTION
**Pull request by Data-drone**
added in Spark 3 with Hadoop 3.2
Scala updated to 2.12

### CODE REVIEW

**Comment by duffar12** [comment]
can you update the docker-compose and k8s-spark-cluster.yaml files with the new spark versions please?

**Comment by Data-drone** [comment]
I have updated the readme and the ymls

**Comment by GezimSejdiu** [comment]
Thanks a lot, @Data-drone for your contribution. 

Take care.

**Comment by Data-drone** [comment]
I don't have the access to do that. In the mean time you build the docker image yourself and run them from your local machine

**Pull request merged**
