### PR TITLE
changed base image from java:8 (jessie debian) to alpine:3.8

### PR DESCRIPTION
**Pull request by gmouchakis**
By moving from Debian to Alpine the image size is reduced by ~500MB.

### CODE REVIEW

**Comment by GezimSejdiu** [comment]
Hi @gmouchakis ,
many thanks for your PR. I just tested it locally and works well and the size has been reduced drastically :). I haven't tested it out but just wanted to be sure that we will not exclude [submit](https://github.com/big-data-europe/docker-spark/tree/master/submit) and [templates](https://github.com/big-data-europe/docker-spark/tree/master/template) ([java](https://github.com/big-data-europe/docker-spark/tree/master/template/java), [python](https://github.com/big-data-europe/docker-spark/tree/master/template/python), [scala](https://github.com/big-data-europe/docker-spark/tree/master/template/scala)) images while we remove the installation of mvn, python, sbt from the base image. I know that we do install them on the template image (e.g. https://github.com/big-data-europe/docker-spark/blob/master/template/java/Dockerfile#L11 ) but would be good if we can test it.

Did you have a chance to test the templates images? I just tested it from the spark-shell and works. If that works as well, I'm okay to merge it. 

Best regards,

**Comment by gmouchakis** [comment]
Hi @GezimSejdiu! I just tested the spark-shell as you did. I have never used the template images (even before the change to alpine) and for this PR i only tested the maven, python and sbt installations in the created images (they work). I was hopping that you would have something ready to test from BDE but since you don't I'll test the templates at some point and let you know.

**Comment by gmouchakis** [comment]
Also, do we support the scala template? In the build script is commented out and if you try to build it it fails, both for alpine and the current base image.

**Comment by GezimSejdiu** [comment]
Right, 
>I was hopping that you would have something ready to test from BDE but since you don't I'll test the templates at some point and let you know.

I can do something here as well, I can run SANSA and see if one of the examples works.
And reg. 
>Also, do we support the scala template? In the build script is commented out and if you try to build it it fails, both for alpine and the current base image.

Yes, we do. There was an issue with the sbt v1.x from sbt-spark-package so we moved to sbt-assamly (see the discussion here : https://github.com/big-data-europe/docker-spark/pull/49 ) . Will merge the latest spark2.4.0 into master branch which solve that issue.

Best regards,

**Comment by shimamoto** [comment]
This PR is great! Do we plan to move this forward? I feel like moving to alpine on some other branches besides master branch. Is there anything I can do?

**Comment by shimamoto** [comment]
Basically, it's a great idea. Just to confirm, this PR will be merged to `master`, right? I mean the base image for the next release of Spark (maybe 2.4.1-hadoop2.7) would be built on Alpine because a branch for its version would be created from `master`.

**Comment by gmouchakis** [comment]
@shimamoto Gezim proposes to maintain a different branch/tags for alpine and continue using debian in the master branch.

@GezimSejdiu I think that it would be simpler to only maintain a single base image but I it is not a big deal to use both. I can keep the proposed alpine branch updated according to future releases and also tag them so users can use the image that best fits their needs.
But what do you mean by "since we should provide java compatibilities for various use-cases"? Alpine also provides Java.

**Comment by GezimSejdiu** [comment]
Hi @gmouchakis ,
Since the size of the images was a bit of concern, keeping alpine as a default would be better I guess. I promise that I will test it on the template image. Let me do it right now since I just created a [demo app](https://github.com/GezimSejdiu/spark-starter) which can be tested out.

As you mention that alpine also provides java/mvn/sbt we could simply use that. If users require jessie debian version in the future we could tag them as well.

Will let you know with the update. 

Once more, many thanks all for your contribution and valuable discussion.

**Comment by gmouchakis** [comment]
Done!

**Pull request merged**
